### ISSUE TITLE
Community move : use the meta-yocto revision

### ISSUE THREAD

**Issue by IniterWorker** [micro-iot/meta-linkit7688#4]
Hello @micro-iot,

I think we need to work a bit to reduce branch-like kernel_xxx and we need to start to maintaining this layer by yocto revision name like warrior, zeus, etc.

B.r

**Comment by micro-iot** [comment]
Hello,
won't do - kernel version is decoupled from the one used in yocto (has been ported from OpenWRT just because of lacking mainline kernel support)
